spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/connect-pro-db
    username: connect-pro
    password: connect-pro
    driver-class-name: org.postgresql.Driver

    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  mail:
    host: 192.168.1.100
#    host: 10.25.104.5
    port: 1025
    username: contact.connect_pro@gmail.com
    password: dev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  
app:
  mail:
    provider: javamail

security:
  otp-token:
    expiration-time: 20

  jwt:
    secret: "lvWNwREIlN4FEIrwApmUwP1EIKaYpFggdZMZMAMFdo8="
    expiration-time: 720

aws:
  region:
    static: us-east-1

  credentials:
    access-key: connect-pro
    secret-key: connect-pro

  s3:
    bucket-name: connect-pro-images
    endpoint: http://192.168.1.100:4566
    bucket-url-prefix: http://192.168.1.100:4566/connect-pro-images/
#    endpoint: http://10.25.104.5:4566
#    bucket-url-prefix: http://10.25.104.5:4566/connect-pro-images/
#    endpoint: http://172.28.176.250:4566
#    bucket-url-prefix: http://172.28.176.250:4566/connect-pro-images/
    
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
